# Generated by Django 4.1 on 2022-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="url",),
        migrations.AlterField(
            model_name="article", name="date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="article", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article", name="title", field=models.CharField(max_length=200),
        ),
    ]
